server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/expense_tracker
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework: INFO
